FROM python:3.8.2-slim

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install pytest==3.7.1

RUN mkdir /simulator/
WORKDIR /simulator/
COPY . /simulator/

ENV PYTHONPATH /simulator/

CMD ["python", "-m", "pytest", "/simulator/tests/", "-vv"]
