version: '3'
services:
  
  simulator:
    build: './simulator'
    volumes:
      - ./db:/simulator/db/
      - ./parameters:/simulator/parameters/

  dash-app:
    build: './dash'
    ports:
      - "8050:8050"
    depends_on:
      - simulator
    volumes:
      - ./db:/dash/db/
      - ./parameters:/dash/parameters/
