FROM conda/miniconda3

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install pytest==3.7.1

RUN mkdir /dash/
WORKDIR /dash/
COPY . /dash/

ENV PYTHONPATH /dash/

CMD ["python", "-m", "pytest", "/dash/tests/", "-vv"]
